name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Install Android SDK + platforms/build-tools via sdkmanager
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Restore google-services.json from repo secret
      - name: Restore google-services.json
        run: |
          mkdir -p app
          cat > app/google-services.json <<'JSON'
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          JSON

      # (Optional) If you also keep a firebase.json, restore it the same way:
      # - name: Restore firebase.json
      #   run: |
      #     cat > firebase.json <<'JSON'
      #     ${{ secrets.FIREBASE_JSON }}
      #     JSON

      # Gradle caching (speeds up builds)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug
        run: ./gradlew assembleDebug
